# Generated by Django 4.2.1 on 2023-09-05 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Title visible as chapter in formula's card", max_length=255, verbose_name="formulas' scope title")),
                ('order', models.IntegerField(help_text="The value determines the order of chapters in formulas's card view", unique=True, verbose_name='order')),
            ],
            options={
                'verbose_name': 'title',
                'verbose_name_plural': 'titles',
            },
        ),
        migrations.CreateModel(
            name='FormulaNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(help_text='Provide note for formula card chapter', verbose_name='formula note')),
                ('order', models.IntegerField(help_text="The value determines the order of notes in formula's chapter view", verbose_name='order')),
                ('title', models.ForeignKey(help_text='The chapter of formula card to which the formula note is linked', on_delete=django.db.models.deletion.CASCADE, to='formulas.title', verbose_name='title')),
            ],
            options={
                'verbose_name': 'formula note',
                'verbose_name_plural': 'formula notes',
            },
        ),
        migrations.AddConstraint(
            model_name='formulanote',
            constraint=models.UniqueConstraint(fields=('title', 'order'), name='unique_order_for_note_in_chapter'),
        ),
    ]
