# Generated by Django 4.2.1 on 2023-07-02 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('program_class', models.IntegerField(verbose_name='class')),
                ('is_extended', models.BooleanField(help_text='Should be checked if chapter belongs to the extended level', verbose_name='is extended')),
                ('order', models.IntegerField(help_text='The value determines the order of chapters in table of content', unique=True, verbose_name='order')),
            ],
            options={
                'verbose_name': 'chapter',
                'verbose_name_plural': 'chapters',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('is_extended', models.BooleanField(help_text='Should be checked if chapter belongs to the extended level', verbose_name='is extended')),
                ('order', models.IntegerField(help_text="The value determines the order of topics in chapter's table of content", verbose_name='order')),
                ('chapter', models.ForeignKey(help_text='The chapter to which the topic is linked', on_delete=django.db.models.deletion.CASCADE, to='chapters.chapter', verbose_name='chapter')),
            ],
            options={
                'verbose_name': 'topic',
                'verbose_name_plural': 'topics',
            },
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('program_class', 'order'), name='unique_order_for_chapters_for_each_class'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('chapter', 'order'), name='unique_order_for_topics_in_chapter'),
        ),
    ]
