# Generated by Django 4.2.1 on 2023-07-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='is_extended',
            field=models.BooleanField(help_text='Should be checked if topic belongs to the extended level', verbose_name='is extended'),
        ),
    ]
