# Generated by Django 4.2.1 on 2023-07-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_noteelement_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteelement',
            name='name',
            field=models.CharField(blank=True, help_text='Resource title for the administrator purpose of management', max_length=128, null=True, verbose_name='name'),
        ),
    ]
