# Generated by Django 4.2.1 on 2023-09-05 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('chapters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'exercise_content',
                    models.TextField(
                        help_text='Describe the content of exercise - the command',
                        verbose_name='exercise content',
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        help_text='Title visible as exercise title in exercises list',
                        max_length=255,
                        verbose_name='exercise title',
                    ),
                ),
                (
                    'is_extended',
                    models.BooleanField(
                        help_text='Should be checked if exercise belongs to the extended level',
                        verbose_name='is extended',
                    ),
                ),
                (
                    'order',
                    models.IntegerField(
                        default=0,
                        help_text="The value determines the order of exercise in exercises' list view",
                        unique=True,
                        verbose_name='order',
                    ),
                ),
                (
                    'topic',
                    models.ForeignKey(
                        help_text='The topic to which the exercise is linked',
                        on_delete=django.db.models.deletion.CASCADE,
                        to='chapters.topic',
                        verbose_name='topic',
                    ),
                ),
            ],
            options={
                'verbose_name': 'exercise',
                'verbose_name_plural': 'exercises',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        help_text='Title visible as step title and for administrator purposes',
                        max_length=255,
                        verbose_name='step title',
                    ),
                ),
                (
                    'instruction',
                    models.TextField(
                        help_text='Describe the instruction for step',
                        verbose_name='instruction',
                    ),
                ),
                (
                    'solution',
                    models.TextField(
                        default=None,
                        help_text='Solution for step visible as hint',
                        verbose_name='instruction',
                    ),
                ),
                (
                    'order',
                    models.IntegerField(
                        help_text="The value determines the order of step in exercise's view",
                        verbose_name='order',
                    ),
                ),
                (
                    'exercise',
                    models.ForeignKey(
                        help_text='The exercise to which the step is linked',
                        on_delete=django.db.models.deletion.CASCADE,
                        to='exercises.exercise',
                        verbose_name='exercise',
                    ),
                ),
            ],
            options={
                'verbose_name': 'step',
                'verbose_name_plural': 'steps',
            },
        ),
        migrations.AddConstraint(
            model_name='step',
            constraint=models.UniqueConstraint(
                fields=('exercise', 'order'), name='unique_order_for_step_in_exercise'
            ),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(
                fields=('topic', 'order'), name='unique_order_for_exercise_in_topic'
            ),
        ),
    ]
