# Generated by Django 4.2.1 on 2023-07-23 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title visible as step title and for administrator purposes', max_length=255, verbose_name='step title')),
                ('instruction', models.TextField(help_text='Describe the instruction for step', verbose_name='instruction')),
                ('order', models.IntegerField(help_text="The value determines the order of step in exercise's view", verbose_name='order')),
                ('exercise', models.ForeignKey(help_text='The exercise to which the step is linked', on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise', verbose_name='exercise')),
            ],
            options={
                'verbose_name': 'step',
                'verbose_name_plural': 'steps',
            },
        ),
        migrations.AddConstraint(
            model_name='step',
            constraint=models.UniqueConstraint(fields=('exercise', 'order'), name='unique_order_for_step_in_exercise'),
        ),
    ]
