# Generated by Django 4.2.1 on 2023-07-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_step_step_unique_order_for_step_in_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='order',
            field=models.IntegerField(default=0, help_text="The value determines the order of exercise in exercises' list view", unique=True, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='step',
            name='order',
            field=models.IntegerField(help_text="The value determines the order of step in exercise's view", unique=True, verbose_name='order'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(fields=('topic', 'order'), name='unique_order_for_exercise_in_topic'),
        ),
    ]
