# Generated by Django 4.2.1 on 2023-07-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_exercise_order_step_solution_alter_step_order_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='step',
            name='unique_order_for_step_in_exercise',
        ),
        migrations.AddConstraint(
            model_name='step',
            constraint=models.UniqueConstraint(fields=('order', 'exercise'), name='unique_order_for_step_in_exercise'),
        ),
    ]
