# Generated by Django 4.2.1 on 2023-07-25 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_remove_step_unique_order_for_step_in_exercise_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='step',
            name='unique_order_for_step_in_exercise',
        ),
    ]
