# Generated by Django 4.2.1 on 2023-07-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_remove_step_unique_order_for_step_in_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='order',
            field=models.IntegerField(help_text="The value determines the order of step in exercise's view", verbose_name='order'),
        ),
        migrations.AddConstraint(
            model_name='step',
            constraint=models.UniqueConstraint(fields=('exercise', 'order'), name='unique_order_for_step_in_exercise'),
        ),
    ]
