# Generated by Django 4.2.1 on 2023-09-05 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chapters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.OneToOneField(help_text='The topic to which the quiz is linked', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chapters.topic', verbose_name='topic')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_content', models.TextField(verbose_name='question content')),
                ('quiz', models.ForeignKey(help_text='The quiz to which the question is linked', on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz', verbose_name='quiz')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_content', models.CharField(max_length=255, verbose_name='answer content')),
                ('is_correct', models.BooleanField(default=False, help_text='Should be checked if the answer is correct for the question', verbose_name='is correct')),
                ('question', models.ForeignKey(help_text='The question to which the answer is linked', on_delete=django.db.models.deletion.CASCADE, to='quizzes.question', verbose_name='question')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answer',
            },
        ),
    ]
