# Generated by Django 4.2.1 on 2023-07-04 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0001_initial'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='chapter',
            field=models.OneToOneField(help_text='The topic to which the quiz is linked', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chapters.topic', verbose_name='topic'),
        ),
    ]
