# Generated by Django 4.2.1 on 2023-07-04 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_quiz_chapter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='chapter',
            new_name='topic',
        ),
    ]
